
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  build:
    name: flare
    arch: "amd64"
    system: "linux,darwin"
    path: "./bin"
    packSrc: "resource,manifest/i18n"
    version: "v0.1.0"
